// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/demo/demo.proto

package demo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DemoRequst struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoRequst) Reset()         { *m = DemoRequst{} }
func (m *DemoRequst) String() string { return proto.CompactTextString(m) }
func (*DemoRequst) ProtoMessage()    {}
func (*DemoRequst) Descriptor() ([]byte, []int) {
	return fileDescriptor_08b73fb6bfa52be9, []int{0}
}

func (m *DemoRequst) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoRequst.Unmarshal(m, b)
}
func (m *DemoRequst) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoRequst.Marshal(b, m, deterministic)
}
func (m *DemoRequst) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoRequst.Merge(m, src)
}
func (m *DemoRequst) XXX_Size() int {
	return xxx_messageInfo_DemoRequst.Size(m)
}
func (m *DemoRequst) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoRequst.DiscardUnknown(m)
}

var xxx_messageInfo_DemoRequst proto.InternalMessageInfo

func (m *DemoRequst) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DemoResponse struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoResponse) Reset()         { *m = DemoResponse{} }
func (m *DemoResponse) String() string { return proto.CompactTextString(m) }
func (*DemoResponse) ProtoMessage()    {}
func (*DemoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08b73fb6bfa52be9, []int{1}
}

func (m *DemoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoResponse.Unmarshal(m, b)
}
func (m *DemoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoResponse.Marshal(b, m, deterministic)
}
func (m *DemoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoResponse.Merge(m, src)
}
func (m *DemoResponse) XXX_Size() int {
	return xxx_messageInfo_DemoResponse.Size(m)
}
func (m *DemoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DemoResponse proto.InternalMessageInfo

func (m *DemoResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*DemoRequst)(nil), "demo.DemoRequst")
	proto.RegisterType((*DemoResponse)(nil), "demo.DemoResponse")
}

func init() {
	proto.RegisterFile("proto/demo/demo.proto", fileDescriptor_08b73fb6bfa52be9)
}

var fileDescriptor_08b73fb6bfa52be9 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x49, 0xcd, 0x85, 0x10, 0x7a, 0x60, 0xbe, 0x10, 0x0b, 0x88, 0xad, 0xa4, 0xc0,
	0xc5, 0xe5, 0x92, 0x9a, 0x9b, 0x1f, 0x94, 0x5a, 0x58, 0x5a, 0x5c, 0x22, 0x24, 0xc4, 0xc5, 0x92,
	0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x2b, 0x29, 0x71, 0xf1,
	0x40, 0x54, 0x14, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x82, 0xd4, 0x94, 0xa4, 0x56, 0x94, 0xc0, 0xd4,
	0x80, 0xd8, 0x46, 0x8e, 0x5c, 0xdc, 0x20, 0x35, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42,
	0x46, 0x5c, 0x1c, 0xc1, 0x89, 0x95, 0x1e, 0xa9, 0x39, 0x39, 0xf9, 0x42, 0x02, 0x7a, 0x60, 0x3b,
	0x11, 0x96, 0x48, 0x09, 0x21, 0x8b, 0x40, 0x0c, 0x55, 0x62, 0x48, 0x62, 0x03, 0xbb, 0xca, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x1b, 0x47, 0x8b, 0xae, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DemoServiceClient is the client API for DemoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DemoServiceClient interface {
	SayHello(ctx context.Context, in *DemoRequst, opts ...grpc.CallOption) (*DemoResponse, error)
}

type demoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDemoServiceClient(cc grpc.ClientConnInterface) DemoServiceClient {
	return &demoServiceClient{cc}
}

func (c *demoServiceClient) SayHello(ctx context.Context, in *DemoRequst, opts ...grpc.CallOption) (*DemoResponse, error) {
	out := new(DemoResponse)
	err := c.cc.Invoke(ctx, "/demo.DemoService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemoServiceServer is the server API for DemoService service.
type DemoServiceServer interface {
	SayHello(context.Context, *DemoRequst) (*DemoResponse, error)
}

// UnimplementedDemoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDemoServiceServer struct {
}

func (*UnimplementedDemoServiceServer) SayHello(ctx context.Context, req *DemoRequst) (*DemoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterDemoServiceServer(s *grpc.Server, srv DemoServiceServer) {
	s.RegisterService(&_DemoService_serviceDesc, srv)
}

func _DemoService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoRequst)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demo.DemoService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServiceServer).SayHello(ctx, req.(*DemoRequst))
	}
	return interceptor(ctx, in, info, handler)
}

var _DemoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "demo.DemoService",
	HandlerType: (*DemoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _DemoService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/demo/demo.proto",
}
